# Generated by Django 5.1.3 on 2024-11-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(to='api.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='step',
            field=models.ManyToManyField(to='api.step'),
        ),
    ]
